name: npm-deploy

on:
  release:
    types: [released]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: install
        run: |
          npm ci
        env:
          CI: true

      - name: test
        run: npm test
        env:
          CI: true

      - name: publish
        run: npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
